import cv2

import numpy as np
import argparse
import time
import os

offset_minus = 5
offset_plus = offset_minus*2

dir = 'Skin melanoma/to process/'
for filename in os.listdir(dir):

	try:
		# Read image
		full_path = dir+filename
		img = cv2.imread(full_path)

		# Copy image
		copy_img = img.copy()

		# Convert image to grayscale
		img_gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY )

		# Gaussian Blur
		gauss_img=cv2.GaussianBlur(img_gray,(7,7),cv2.BORDER_DEFAULT)

		# OTSU threshold
		otsu_threshold, img_thresh = cv2.threshold(gauss_img, 0, 255, cv2.THRESH_BINARY_INV + cv2.THRESH_OTSU)

		# Find contours
		# cnts, hier = cv2.findContours(img_thresh, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
		cnts, hier = cv2.findContours(img_thresh, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)

		# Obtain bounding box, extract and save ROI
		if len(cnts) > 0:
			max_cnt = max(cnts, key = cv2.contourArea)
			cv2.drawContours(img, cnts, -1, (0,255,0), 2)
			x,y,w,h = cv2.boundingRect(max_cnt)
			cv2.rectangle(img, (x-offset_minus, y-offset_minus), (x + w + offset_plus, y + h + offset_plus), (0,255,0), 2)
			ROI = gauss_img[y-offset_minus:y-offset_minus+h+offset_plus, x-offset_minus:x-offset_minus+w+offset_plus]

			cv2.imshow("IMG", img)
			cv2.waitKey(0)

		# # variables for GrabCut algorithm
		# rectangle_coordinates=(x-offset_minus, y-offset_minus, x + w + offset_plus, y + h + offset_plus)
		# fgModel = np.zeros((1, 65), dtype="float")
		# bgModel = np.zeros((1, 65), dtype="float")
		# mask = np.zeros(gauss_img.shape[:2], dtype="uint8")

		# gauss_img_color = cv2.cvtColor(gauss_img, cv2.COLOR_GRAY2BGR)

		# start = time.time()
		# (mask, bgModel, fgModel) = cv2.grabCut(gauss_img_color, mask, rectangle_coordinates, bgModel, fgModel, iterCount=5, mode=cv2.GC_INIT_WITH_RECT)
		# end = time.time()
		# print("[INFO] applying GrabCut took {:.2f} seconds".format(end - start) + " for " + full_path)

		# values = (
		# 	("Definite Background", cv2.GC_BGD),
		# 	("Probable Background", cv2.GC_PR_BGD),
		# 	("Definite Foreground", cv2.GC_FGD),
		# 	("Probable Foreground", cv2.GC_PR_FGD),
		# )
		# # loop over the possible GrabCut mask values
		# for (name, value) in values:
		# 	# construct a mask that for the current value
		# 	# print("[INFO] showing mask for '{}'".format(name))
		# 	valueMask = (mask == value).astype("uint8") * 255
		# 	# # display the mask so we can visualize it
		# 	# cv2.imshow(name, valueMask)
		# 	# cv2.waitKey(0)

		# # we'll set all definite background and probable background pixels
		# # to 0 while definite foreground and probable foreground pixels are
		# # set to 1
		# outputMask = np.where((mask == cv2.GC_BGD) | (mask == cv2.GC_PR_BGD), 0, 1)
		# # scale the mask from the range [0, 1] to [0, 255]
		# outputMask = (outputMask * 255).astype("uint8")
		# # apply a bitwise AND to the image using our mask generated by
		# # GrabCut to generate our final output image
		# output = cv2.bitwise_and(gauss_img, gauss_img, mask=outputMask)
		# output = output[y - offset_minus : y - offset_minus + h + offset_plus, x - offset_minus : x - offset_minus + w + offset_plus]


		# # show the input image followed by the mask and output generated by
		# # GrabCut and bitwise masking
		# # cv2.imshow("Input", gauss_img)
		# # cv2.imshow("GrabCut Mask", outputMask)
		# cv2.imshow("GrabCut Output", output)
		# cv2.waitKey(0)


		# # Save ROI image
		# cv2.imwrite('test.jpg', ROI)
		# cv2.imwrite('out_melanoma.jpg', output)
	except:
		print("[ERROR] something went wrong for "+full_path)